### ISSUE TITLE
README: Software Requirements

### ISSUE THREAD

**Issue by DennisRas** [MrEliasen/path-to-power#64]
Add software requirements to the README files.
Being sleepy when running the server for the first time I obviously forgot about [installing MongoDB](https://www.mongodb.com/download-center#production) 😄 

> { MongoError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (D:\Projekter\path-to-power\server\node_modules\mongodb-core\lib\topologies\server.js:503:11)
    at emitOne (events.js:115:13)
    at Pool.emit (events.js:210:7)
    at Connection.<anonymous> (D:\Projekter\path-to-power\server\node_modules\mongodb-core\lib\connection\pool.js:326:12)
    at Object.onceWrapper (events.js:318:30)
    at emitTwo (events.js:125:13)
    at Connection.emit (events.js:213:7)
    at Socket.<anonymous> (D:\Projekter\path-to-power\server\node_modules\mongodb-core\lib\connection\connection.js:245:50)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
  name: 'MongoNetworkError',
  message: 'failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]' }

**Comment by MrEliasen** [comment]
Good point! I completely forgot about that.
